apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: staging
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskflow_users"
  LOG_LEVEL: "info"
  JWT_EXPIRY: "3600"