kube-prometheus-stack:
  grafana:
    adminPassword: "admin"

alertmanagerConfig:
  smtp:
    host: ""
    from: ""
    username: "<smtp-username-brevo>"
    password: "<smtp-password-brevo>"
    to: ""
