apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-cm
  namespace: staging
data:
  NODE_ENV: "production"
  PORT: "3002"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskflow_tasks"
  LOG_LEVEL: "info"
  REDIS_URL: "redis://redis:6379"
