apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: taskflow-task-service:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
              protocol: TCP
          envFrom:
            - configMapRef:
                name: task-service-cm
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-service-secret
                  key: db-password
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /does-not-exist
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
