#!/bin/bash

# Script de test complet pour reproduire tous les résultats du TP Partie 2
# Exécuter étape par étape dans des terminaux différents

echo "=========================================="
echo "TP PARTIE 2 - Script d'Exécution Complet"
echo "=========================================="

# ============================================
# TERMINAL 1: Démarrer l'infrastructure
# ============================================

echo ""
echo ">>> TERMINAL 1: Lancer l'infra (observabilité + services)"
echo "npm run dev:infra"
echo ""
echo "Attendez que tous les services soient up:"
echo "  ✓ postgres"
echo "  ✓ redis"
echo "  ✓ otel-collector"
echo "  ✓ prometheus"
echo "  ✓ tempo"
echo "  ✓ grafana"
echo "  ✓ api-gateway"
echo "  ✓ task-service, user-service, notification-service"
echo "  ✓ frontend"
echo ""

# ============================================
# TERMINAL 2: Préparer les credentials
# ============================================

echo ""
echo ">>> TERMINAL 2: Préparer les credentials JWT"
echo ""

echo "1. Créer un compte utilisateur (ou se logger):"
echo "   Ouvrir http://localhost:5173"
echo "   Login avec: email=test@example.com, password=Test@1234"
echo ""

echo "2. Récupérer le token JWT:"
echo "   Option A: DevTools (F12) → Application → LocalStorage → token"
echo "   Option B: curl:"
echo ""
echo "   curl -X POST http://localhost:4000/api/users/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"test@example.com\",\"password\":\"Test@1234\"}' | jq '.token'"
echo ""

echo "3. Sauvegarder le token:"
echo "   export TOKEN='eyJhbGc...'"
echo "   export EMAIL='test@example.com'"
echo "   export PASSWORD='Test@1234'"
echo ""

# ============================================
# TERMINAL 3: Exécuter les tests K6
# ============================================

echo ""
echo "=========================================="
echo ">>> TERMINAL 3: Exécuter les tests K6"
echo "=========================================="
echo ""

echo "ÉTAPE 1: TEST LÉGER (Q1-Q2)"
echo "==============================="
echo ""
echo "Commande:"
echo "  k6 run -e TOKEN=\$TOKEN scripts/load-test-light.js"
echo ""
echo "Résultats attendus:"
echo "  ✓ http_req_duration p95: ~85ms"
echo "  ✓ http_req_failed: 0%"
echo "  ✓ checks_failed: 0%"
echo ""
echo "Durée: ~30 secondes"
echo ""

echo ""
echo "ÉTAPE 2: TEST RÉALISTE (Q3-Q5)"
echo "==============================="
echo ""
echo "Commande:"
echo "  k6 run -e EMAIL=\$EMAIL -e PASSWORD=\$PASSWORD scripts/load-test-realistic.js"
echo ""
echo "À faire EN PARALLÈLE:"
echo "  - Ouvrir Grafana: http://localhost:3000"
echo "  - Panel 'Request Rate per Service' → voir le pic à 50 VUs"
echo "  - Panel 'Latency p50/p95/p99' → noter qu'il reste flat!"
echo ""
echo "Phases observées:"
echo "  [0-30s] Ramp-up 0→10 VUs"
echo "    → p95: ~150ms, checks: 100% ✓"
echo ""
echo "  [30-90s] Hold 10 VUs"
echo "    → p95: ~180ms, checks: 95% ✓"
echo ""
echo "  [90-120s] Spike 10→50 VUs"
echo "    → p95: ~500-600ms, checks: ~70% ✗ commence à échouer"
echo ""
echo "  [120-180s] Hold 50 VUs"
echo "    → p95: ~680ms, checks: ~70% ✗ stable mais dégradé"
echo ""
echo "  [180-210s] Ramp-down 50→0 VUs"
echo "    → p95: retour progressif vers ~150ms"
echo ""
echo "Résumé final attendu:"
echo "  ✓ checks: ~75% (passé), ~25% échoué"
echo "  ✓ http_req_duration p95: ~680ms (8× test léger!)"
echo "  ✓ checks_failed par type:"
echo "      - login: 100%"
echo "      - tasks < 500ms: ~70% ← CRITIQUE"
echo ""
echo "Durée: ~3 minutes"
echo ""

# ============================================
# TERMINAL 4: Observer Grafana & Prometheus
# ============================================

echo ""
echo "=========================================="
echo ">>> TERMINAL 4: Observer l'observabilité"
echo "=========================================="
echo ""

echo "Ouvrir Grafana pendant le test réaliste:"
echo "  http://localhost:3000 (login: admin / admin)"
echo ""
echo "Panels à observer:"
echo ""
echo "1. Request Rate per Service"
echo "   → Voir les ratios:"
echo "     Gateway: 200 req/s"
echo "     Task-service: 100 req/s (2×)"
echo "     User-service: 50 req/s"
echo "     Notif-service: 50 req/s"
echo ""
echo "2. Latency p50/p95/p99"
echo "   → Observe qu'il reste PLAT vers 100-150ms"
echo "     Même pendant le spike!"
echo "     Pourquoi? Il ne mesure que le processing, pas la queue"
echo ""
echo "3. Error Rate 5xx"
echo "   → Affiche 'No data'"
echo "     Car les services ne retournent pas de 500s"
echo "     Seulement des timeouts (jamais loggés en HTTP)"
echo ""

echo "Ouvrir Prometheus:"
echo "  http://localhost:9090/targets"
echo ""
echo "Targets observés:"
echo "  ✓ task-service:3002 (UP)"
echo "  ✓ user-service:3001 (UP)"
echo "  ✓ notification-service:3003 (UP)"
echo ""

# ============================================
# TERMINAL 5-6: Tester le scaling (Q6-Q7)
# ============================================

echo ""
echo "=========================================="
echo ">>> TERMINAL 5: Scaling (Q6-Q7)"
echo "=========================================="
echo ""

echo "AVANT la correction:"
echo "==================="
echo ""
echo "Essayer de scaler (va échouer):"
echo "  docker compose down"
echo "  docker compose up --scale task-service=3"
echo ""
echo "Résultat attendu: ERREUR"
echo "  Error response from daemon: Ports are not available:"
echo "  ports 3002/tcp is already allocated"
echo ""

echo ""
echo "APRÈS la correction:"
echo "===================="
echo ""
echo "Appliquer le fix Docker:"
echo ""
echo "1. Backup:"
echo "   cp docker-compose.yml docker-compose.yml.bak"
echo ""
echo "2. Modifier docker-compose.yml:"
echo "     - Enlever les 'ports:' de: task-service, user-service, notification-service"
echo "     - Enlever les 'ports:' de: api-gateway (garder 4000:4000)"
echo "     - Enlever les 'ports:' de: frontend (garder 5173:80)"
echo "     - Ajouter un 'networks:' section"
echo ""
echo "   Ou simplement utiliser docker-compose.yml.fixed:"
echo "   cp docker-compose.yml.fixed docker-compose.yml"
echo ""

echo "3. Relancer avec scaling:"
echo "   docker compose up --scale task-service=3"
echo ""
echo "Résultat attendu: ✅ SUCCESS"
echo "  - task-service_1, task-service_2, task-service_3 démarrent"
echo "  - Pas d'erreur de port (ports non mappés publiquement)"
echo ""

echo "4. Vérifier la distribution:"
echo "   docker compose logs task-service | tail -30"
echo ""
echo "   Ou relancer un test K6:"
echo "   k6 run -e EMAIL=\$EMAIL -e PASSWORD=\$PASSWORD scripts/load-test-realistic.js"
echo ""
echo "   Résultat:"
echo "   ✅ Les 3 replicas reçoivent du trafic"
echo "   ✅ Latence s'améliore: p95 ~400ms (vs 680ms)"
echo "   ✅ Throughput meilleur"
echo ""

echo "5. Prometheus peut-il voir les 3 replicas?"
echo "   http://localhost:9090/targets"
echo ""
echo "   ❌ NON, toujours qu'une seule cible:"
echo "      task-service:3002 (UP)"
echo ""
echo "   Pourquoi?"
echo "   - Prometheus utilise config statique: targets: ['task-service:3002']"
echo "   - 'task-service' résout à UNE VIP Docker interne"
echo "   - VIP = load balance transparent, mais une seule adresse"
echo "   - Les 2 autres replicas existent mais sont invibles"
echo ""

# ============================================
# REMARQUES FINALES
# ============================================

echo ""
echo "=========================================="
echo "Remarques Importantes"
echo "=========================================="
echo ""

echo "1. Vérifier les credentials"
echo "   - Créer un compte via http://localhost:5173"
echo "   - Ou utiliser les fixtures"
echo ""

echo "2. K6 output"
echo "   - Chercher dans le résumé final les lignes:"
echo "     http_req_duration"
echo "     http_req_failed"
echo "     checks"
echo ""

echo "3. Grafana"
echo "   - Actualiser les panels avec le bouton 'Refresh' (haut-droit)"
echo "   - Changer l'intervalle de temps: '5m' ou 'Last 10m'"
echo "   - Les métriques se mettent à jour toutes les 15s (scrape Prometheus)"
echo ""

echo "4. Captures d'écran"
echo "   - Pour la question 4-5: capturer 'Request Rate per Service' pendant le pic"
echo "   - Pour la question 6: capturer l'erreur Docker"
echo "   - Pour la question 3: copier-coller le résumé K6 terminal"
echo ""

echo ""
echo "✅ Tous les fichiers livrables ont été générés:"
echo "   - ANSWERS.md (réponses concentrées)"
echo "   - REPORT.md (analyse complète)"
echo "   - TEST_RESULTS.md (guide pratique + résultats attendus)"
echo "   - docker-compose.yml.fixed (version corrigée)"
echo "   - scripts/improved-instrumentation.js (instrumenter la queue)"
echo "   - infra/grafana_panels_additions.json (nouveaux panels)"
echo ""

